# Project information
site_name: Tricks
site_url: https://haysberg.github.io/tricks/
site_author: Téo Haÿs
site_description: >-
  Ma doc perso de devops noeuil

# Repository
repo_name: haysberg/tricks
repo_url: https://github.com/haysberg/tricks
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024 Téo Haÿs

# Config thème
theme:
  name: material
  language: fr
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    logo: material/pipe-wrench
  features:
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.action.edit
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.prune
    - navigation.path
    - toc.follow
    - toc.integrate
    - content.tooltips
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair
    

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - footnotes
  - toc:
      permalink: true
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true

# Extra
extra:
  generator: false